
#----------Nødvendig----------------------------------------------------------------------
bilde: https://github.com/paspvik/plainside/blob/gh-pages/assets/img/py.png?raw=true #Fagbilde
name: Sok-1400 Introduksjon til python #Fagtittel
semester: Høst 2021

#--------------Valgfritt---------------------------------------------------------------------
topbox-farge: a6bbc8

contentbox-farge:
contentbox-skygge: 0px 0px 100px 0px rgba(50, 50, 50, 1)

bakgrunn: 
bakgrunn-farge: 

#Farge tekst
primaerfarge: CB333B #Farge overskrifter
sekundaerfarge: #Farge generell tekst
linkfarge: 0e1111 #Farge linker

uitlogo: https://uit.no/ressurs/uit/profil2019/navnetrekk/bokmal_main.svg 
title: null #Skal stå tom
